### ISSUE TITLE
Add versioned deployment

### ISSUE THREAD

**Issue by shanejonas** [MetaMask/iframe-execution-environment#33]
We need to establish a form of versioned deployment for the static iframe execution environment service web page so that we can break the service API without breaking Snaps execution in production.

Currently, the URL of the production environment is:
- `https://metamask.github.io/iframe-execution-environment/`

We will simply append the version of each release to this URL and hard-code the correct version into the MetaMask application. For example, version `1.2.0` would have the following url:
- `https://metamask.github.io/iframe-execution-environment/1.2.0`

#### Notes
- This will require modifying our GitHub Action workflows, and potentially modifying the action we use to deploy to GitHub pages.
- This ticket is distinct from establishing a staging environment, which will be tracked elsewhere.

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps--Core-615b3a7c08d2b20015eb6c4e/issues/MetaMask/iframe-execution-environment/33?planning-poker) with ZenHub @shanejonas @Gudahtt @hmalik88

**Comment by rekmarks** [comment]
Closed by #38.
